INSERT INTO public.users(id, name, gravatar) VALUES (1,'Colin','http://www.gravatar.com/avatar/a51972ea936bc3b841350caef34ea47e?s=64&amp;d=monsterid');
INSERT INTO public.users(id, name, gravatar) VALUES (2,'Kyle','http://www.gravatar.com/avatar/432f3e353c689fc37af86ae861d934f9?s=64&amp;d=monsterid');
INSERT INTO public.users(id, name, gravatar) VALUES (3,'Thomas','http://www.gravatar.com/avatar/48009c6a27d25ef0ea03f985d1f186b0?s=64&amp;d=monsterid');
INSERT INTO public.users(id, name, gravatar) VALUES (4,'James','http://www.gravatar.com/avatar/9372f138140c8578c82bbc77b2eca602?s=64&amp;d=monsterid');

INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (1,'Losenoid','blue','9.99',51,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (2,'Rowlow','red','4.04',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (3,'Printure','green','5.55',18,false);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (4,'Claster','off-white','12.56',9,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (5,'Pepelexa hi','purple','0.99',0,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (6,'Dropellet','speckled','16.00',99,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (7,'Jeebus','depends on the viewing angle','18.11',36,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (8,'Nodile','red','50.00',20,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (9,'Kaloobon','white','8.00',40,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (10,'Bioyino','turtle-shell','90.12',3,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (11,'Dizoolexa','magenta','67.23',976,false);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (12,'Skippy','green','0.01',404,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (13,'what','black','50.00',4,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (14,'My id is actually 333','purple','600.00',900,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (15,'Test','blue','7.77',13,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (16,'Testing','red','4.00',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (17,'Testing','test','4.00',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (18,'Testing','test','4.00',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (19,'Testing','test','NaN',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (20,'Testing','test','NaN',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (21,'Testing','test','NaN',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (22,'Testing','test','2.88',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (23,'Testing','test','1.00',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (24,'Testing','test','1.00',7,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (25,'Testing','test','1.00',null,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (26,'Testing','test','1.00',null,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (27,'Testing','test','1.00',52,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (28,'Testing','test','1.00',52,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (29,'Testing','test','6.75',52,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (30,'Losenoid','blue','9.99',51,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (31,'testing 123','red','123.00',123,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (32,'xyz','red','123.00',0,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (33,'test 123','red','123.00',1,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (34,'test 123','red','123.00',null,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (35,'test 123','red','NaN',null,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (36,'testing 123','red','123.00',1,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (37,'testing 123','purple','123.00',123,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (38,'testing 321','blue','321.00',111,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (39,'testing 123','black','111.00',111,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (40,'xxy','purple','123123.00',555,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (41,'test','turtle-shell','123.00',111,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (42,'new widget','blue','111.00',123,true);
INSERT INTO public.widgets(id, name, color, price, inventory, melts) VALUES (43,'Tester','magenta','10.00',null,true);